routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientServiceController;
use App\Http\Controllers\PatientServiceAjaxController;
use App\Http\Controllers\ResourceController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ServiceTypesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PatientSenderController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\PatientCardController;
use App\Http\Controllers\SmsController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\DebitController;
use App\Http\Controllers\DebitProductsController;
use App\Http\Controllers\ServiceProductController;
use App\Http\Controllers\OutputController;
use App\Http\Controllers\UserController;
use App\Models\Patient;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ping', function(){

    return Carbon::now()->startOfYear()->toDateString();
});

Route::get('/prices/{service_type_id}', [PrintController::class,'generatePrices']);



Route::post('/webhook/{token}/callback', [TelegramController::class,'handle'])->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]);;


// Route::post('/patient-services/export', [PatientServiceAjaxController::class, 'index'])->name('patient-services.api.index');
Route::get('patient/profile/{code?}',[PatientController::class,'profile'])->name('patient.login');
Route::get('patient/detail',[PatientController::class,'profileDetail'])->name('patient.profile');
Route::get('patient/logout/{id}',[PatientController::class,'logout'])->name('patient.logout');


Route::middleware(['auth'])->group(function(){

    Route::get('/', [HomeController::class,'index'])->name('home');
     Route::get('/home', [HomeController::class,'index'])->name('home.welcome');
    Route::get('/dashboard/{range}', [DashboardController::class,'statistic'])->name('dashboard.statistic');

    Route::get('/sms/index', [SmsController::class, 'index'])->name('sms.index');
    Route::post('/sms/send', [SmsController::class, 'send'])->name('sms.send');
    Route::get('/seach-patients/{phone}', [SmsController::class, 'ajax']);


    Route::resource('patients',PatientController::class);


    Route::resource('service-types',ServiceTypesController::class);



    Route::get('patients', [PatientController::class,'index'])->name('patients.index');

    // Route::delete('patients-services/delete/{patient_service}', [PatientServiceController::class,'delete'])->name('patient-services.delete');

    //repetition
    Route::get('repetition/create/{patient_id?}', [PatientServiceController::class,'createRepetetion'])->name('repetition.create');
    Route::post('repetition', [PatientServiceController::class,'storeRepetetion'])->name('repetition.store');


    Route::resource('patient-services',PatientServiceController::class);
    Route::prefix('excel')->group(function () {
        Route::get('patient-services',[PatientServiceController::class,'excelExport'])->name('patient-services.excel'); 
    });
    Route::resource('doctors',DoctorController::class);
    Route::resource('services',ServiceController::class);


    Route::get('/print/{service_id}', [PrintController::class, 'printConclusion'])->name('printConclusion');
    Route::get('/print-recommendation/{service_id}', [PrintController::class, 'printRecommendation'])->name('printRecommendation');
    Route::get('/print/check/{patient_id}', [ PrintController::class,'printCheck'])->name('print.check');

    //payment
    Route::get('/patients-for-cashier', [ PatientServiceController::class,'patientsForCashier'])->name('patient-services.cashier');
    Route::get('/get-patient-services/{patient_id}', [ PatientServiceController::class,'getPatientServices'])->name('get-patient-services');

    Route::post('/confirm', [ PatientServiceController::class,'paymentConfirm'])->name('payment.confirm');
    Route::get('/patients-services/profile/{patient_service}', [ PatientServiceController::class,'profile'])->name('patient-services.profile');
    Route::get('/patients-services/for-patient/{patient_service}', [ PatientServiceController::class,'forPatient'])->name('patient.service-details');

    //conclusion

    Route::get('/payed-services', [ PatientServiceController::class,'getPayedServices'])->name('patient-services.payed');
    Route::post('/save-conlusion', [ PatientServiceController::class,'saveConclusion'])->name('patient-services.conclusion');


    Route::get('/resources/cities/{region_id}', [ResourceController::class,'getCitiesByRegion']);
    Route::get('/resources/diagnostics/{service_type_id}', [ResourceController::class,'getDiagnosticTypes']);
    Route::get('/resources/services/{service_type_id}/{diagnostic_type_id?}', [ResourceController::class,'getServices']);
    Route::get('/resources/service-types', [ResourceController::class,'getServiceTypes']);
    Route::get('/resources/debit-products', [ResourceController::class,'getDebitProducts']);



    //reports

    Route::get('/reports/all', [ReportController::class, 'all'])->name('reports.all');
    Route::get('/reports/by-patient-senders', [ReportController::class, 'bySenders'])->name('reports.bysenders');




    Route::resource('patient-senders',PatientSenderController::class);

    Route::get('/sended-patients/{patient_sender}', [PatientServiceController::class, 'getSendedPatients'])->name('patients.sended');

    Route::resource('discounts',DiscountController::class);

    Route::resource('cards',PatientCardController::class);

    // debits
    Route::resource('/debits', DebitController::class);
    // Route::get('/debits/{id}/edit', [DebitController::class,'createRepetetion'])->name('repetition.create');

    // debit_products
    Route::resource('/debit-products', DebitProductsController::class);


    Route::resource('/service-products', ServiceProductController::class);

    
    Route::get('/outputs', [OutputController::class,'index']);

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class,'index'])->name('users.index');
        Route::post('/', [UserController::class,'store'])->name('users.store');
        Route::get('/create', [UserController::class,'create'])->name('users.create');
    });
    

});



Auth::routes();

app/Models/Discount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Discount extends Model
{
    protected $guarded = [];

    protected $attributes = [
        'is_active' => true,
    ];



    use HasFactory;
}

app/Http/Controllers/DiscountController.php
<?php

namespace App\Http\Controllers;

use App\Models\Discount;
use Illuminate\Http\Request;

class DiscountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $discounts = Discount::all();

        return view('discounts.index', [
            'discounts' => $discounts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discounts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'=> 'required',
            'percentage' => 'required'    
        ];

        $inputs = $request->validate($rules);
        
        $discount = Discount::create($inputs);
        
        if($discount){
            return redirect()->route('discounts.index');
        }

        return 'Xatolik sodir bo\'ldi';
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function show(Discount $discount)
    {
        return view('discounts.show', [
            'discount' => $discount
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function edit(Discount $discount)
    {
        
        return view('discounts.edit',[
            'discount' => $discount
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Discount $discount)
    {
        $rules = [
            'name'=> 'required',
            'percentage' => 'required',
            'is_active' => 'required'    
        ];

        $inputs = $request->validate($rules);
        
        $updatedDiscount = $discount->update($inputs);
        
        if($updatedDiscount){
            return redirect()->route('discounts.index');
        }

        return 'Xatolik sodir bo\'ldi update qilishda';
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function destroy(Discount $discount)
    {
        //
    }
}

resources/views/discounts/create.blade.php
@extends('layouts.app')
@section('content')
	<div class="pd-20 card-box mb-30">
		<div class="clearfix mb-30">
			<div class="text-center">
				<h4 class="text-blue h4"> Yangi chegirma qo'shish </h4>
			</div>
		</div>
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
				@if ($errors->has('email'))
				@endif
			</div>
		@endif
		<form method="POST" action="{{ route('discounts.store') }}">
			@csrf
			<div id="discounts">
				<div class="row">
					<div class="col-md-4 col-sm-12">
						<div class="form-group">
							<input class="form-control"  type="text"  placeholder="Chegirma nomi: Yanvar 20% li" name="name">
						</div>
					</div>
					<div class="col-md-2 col-sm-12">
						<div class="form-group">
							<input type="text" class="form-control"  placeholder="Chegirma miqdori (%)" name="percentage">
						</div>
					</div>
				</div>
			</div>
			<hr>
	
			<br>
			<div class="row">
				<div class="form-group offset-11">
					<button type="submit" class="btn btn-primary">Saqlash</button>
				</div>
			</div>
		</form>
	</div>
@endsection

resources/views/discounts/edit.blade.php
@extends('layouts.app')
@section('content')
	<div class="pd-20 card-box mb-30">
		<div class="clearfix mb-30">
			<div class="text-center">
				<h4 class="text-blue h4"> Chegirmani tahrirlash  </h4>
			</div>
		</div>
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
				@if ($errors->has('email'))
				@endif
			</div>
		@endif
		<form method="POST" action="{{ route('discounts.update', ['discount' => $discount->id]) }}">
            @csrf
            {{ method_field('PUT') }}
			<div id="discounts">
				<div class="row">
					<div class="col-md-4 col-sm-12">
						<div class="form-group">
							<input class="form-control"  type="text"  value="{{ $discount->name }}" name="name">
						</div>
					</div>
					<div class="col-md-2 col-sm-12">
						<div class="form-group">
							<input type="text" class="form-control"  value="{{ $discount->percentage }}" name="percentage">
						</div>
					</div>
					<div class="col-md-1 col-sm-12">
						%
					</div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label for="active">Chegirma faolligi </label>

                        <!-- <input type="checkbox" name=""checked data-size="small" class="switch-btn" data-color="#0099ff"> -->
                        
                        <select name="is_active" class="form-control" id="is_active">
                            <option value="1" {{ $discount->is_active ? 'selected' : ''}}>Faol</option>
                            <option value="0" {{ $discount->is_active ? '' : 'selected'}}>Faol emas</option>
                        </select>
                    </div>
                </div>
			</div>
			<hr>
	
			<br>
			<div class="row">
				<div class="form-group offset-11">
					<button type="submit" class="btn btn-primary">Saqlash</button>
				</div>
			</div>
		</form>
	</div>
@endsection

resources/views/discounts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="pd-20 card-box mb-30">
	<div class="clearfix mb-20">
		<div class="text-center">
			<h4 class="text-blue h4">Chegirmalar ro'yxati</h4>
		</div>
		<div class="pull-right">
			<a href="{{ route('discounts.create') }}" class="btn btn-primary btn-sm scroll-click">Chegirma qo'shish  </a>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-bordered table-striped" id="myTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Chegirma nomi</th>
					<th>Chegirma miqdori</th>
					<th>Chegirma holati</th>
					<th>Chegirma qo'shilgan vaqt</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@forelse($discounts as $discount)
					<tr>
						<td>{{ $loop->index+1 }}</td>
                    	<td> {{ $discount->name }}</td>
                        <td> {{ $discount->percentage }} %</td>
						<td> {{ $discount->is_active ? 'Faol' : 'Faol emas' }}</td>	
						<td> {{ $discount->created_at }}</td>
						<td><a href="{{ route('discounts.edit', ['discount'=>$discount->id])}}" class="btn btn-success">Tahrirlash</a></td>
					</tr>
				@empty
					<tr>
						<td colspan="6">Ma'lumotlar topilmadi</td>
					</tr>
				@endforelse	
			</tbody>
			
		</table>
	</div>
</div>	
@endsection


	<!-- <script src="/vendor/datatables/buttons.server-side.js"></script> -->