routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientServiceController;
use App\Http\Controllers\PatientServiceAjaxController;
use App\Http\Controllers\ResourceController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ServiceTypesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PatientSenderController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\PatientCardController;
use App\Http\Controllers\SmsController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\DebitController;
use App\Http\Controllers\DebitProductsController;
use App\Http\Controllers\ServiceProductController;
use App\Http\Controllers\OutputController;
use App\Http\Controllers\UserController;
use App\Models\Patient;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ping', function(){

    return Carbon::now()->startOfYear()->toDateString();
});

Route::get('/prices/{service_type_id}', [PrintController::class,'generatePrices']);



Route::post('/webhook/{token}/callback', [TelegramController::class,'handle'])->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]);;


// Route::post('/patient-services/export', [PatientServiceAjaxController::class, 'index'])->name('patient-services.api.index');
Route::get('patient/profile/{code?}',[PatientController::class,'profile'])->name('patient.login');
Route::get('patient/detail',[PatientController::class,'profileDetail'])->name('patient.profile');
Route::get('patient/logout/{id}',[PatientController::class,'logout'])->name('patient.logout');


Route::middleware(['auth'])->group(function(){

    Route::get('/', [HomeController::class,'index'])->name('home');
     Route::get('/home', [HomeController::class,'index'])->name('home.welcome');
    Route::get('/dashboard/{range}', [DashboardController::class,'statistic'])->name('dashboard.statistic');

    Route::get('/sms/index', [SmsController::class, 'index'])->name('sms.index');
    Route::post('/sms/send', [SmsController::class, 'send'])->name('sms.send');
    Route::get('/seach-patients/{phone}', [SmsController::class, 'ajax']);


    Route::resource('patients',PatientController::class);


    Route::resource('service-types',ServiceTypesController::class);



    Route::get('patients', [PatientController::class,'index'])->name('patients.index');

    // Route::delete('patients-services/delete/{patient_service}', [PatientServiceController::class,'delete'])->name('patient-services.delete');

    //repetition
    Route::get('repetition/create/{patient_id?}', [PatientServiceController::class,'createRepetetion'])->name('repetition.create');
    Route::post('repetition', [PatientServiceController::class,'storeRepetetion'])->name('repetition.store');


    Route::resource('patient-services',PatientServiceController::class);
    Route::prefix('excel')->group(function () {
        Route::get('patient-services',[PatientServiceController::class,'excelExport'])->name('patient-services.excel'); 
    });
    Route::resource('doctors',DoctorController::class);
    Route::resource('services',ServiceController::class);


    Route::get('/print/{service_id}', [PrintController::class, 'printConclusion'])->name('printConclusion');
    Route::get('/print-recommendation/{service_id}', [PrintController::class, 'printRecommendation'])->name('printRecommendation');
    Route::get('/print/check/{patient_id}', [ PrintController::class,'printCheck'])->name('print.check');

    //payment
    Route::get('/patients-for-cashier', [ PatientServiceController::class,'patientsForCashier'])->name('patient-services.cashier');
    Route::get('/get-patient-services/{patient_id}', [ PatientServiceController::class,'getPatientServices'])->name('get-patient-services');

    Route::post('/confirm', [ PatientServiceController::class,'paymentConfirm'])->name('payment.confirm');
    Route::get('/patients-services/profile/{patient_service}', [ PatientServiceController::class,'profile'])->name('patient-services.profile');
    Route::get('/patients-services/for-patient/{patient_service}', [ PatientServiceController::class,'forPatient'])->name('patient.service-details');

    //conclusion

    Route::get('/payed-services', [ PatientServiceController::class,'getPayedServices'])->name('patient-services.payed');
    Route::post('/save-conlusion', [ PatientServiceController::class,'saveConclusion'])->name('patient-services.conclusion');


    Route::get('/resources/cities/{region_id}', [ResourceController::class,'getCitiesByRegion']);
    Route::get('/resources/diagnostics/{service_type_id}', [ResourceController::class,'getDiagnosticTypes']);
    Route::get('/resources/services/{service_type_id}/{diagnostic_type_id?}', [ResourceController::class,'getServices']);
    Route::get('/resources/service-types', [ResourceController::class,'getServiceTypes']);
    Route::get('/resources/debit-products', [ResourceController::class,'getDebitProducts']);



    //reports

    Route::get('/reports/all', [ReportController::class, 'all'])->name('reports.all');
    Route::get('/reports/by-patient-senders', [ReportController::class, 'bySenders'])->name('reports.bysenders');




    Route::resource('patient-senders',PatientSenderController::class);

    Route::get('/sended-patients/{patient_sender}', [PatientServiceController::class, 'getSendedPatients'])->name('patients.sended');

    Route::resource('discounts',DiscountController::class);

    Route::resource('cards',PatientCardController::class);

    // debits
    Route::resource('/debits', DebitController::class);
    // Route::get('/debits/{id}/edit', [DebitController::class,'createRepetetion'])->name('repetition.create');

    // debit_products
    Route::resource('/debit-products', DebitProductsController::class);


    Route::resource('/service-products', ServiceProductController::class);

    
    Route::get('/outputs', [OutputController::class,'index']);

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class,'index'])->name('users.index');
        Route::post('/', [UserController::class,'store'])->name('users.store');
        Route::get('/create', [UserController::class,'create'])->name('users.create');
    });
    

});



Auth::routes();

app/Models/ServiceProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ServiceProduct extends Model
{
    protected $fillable = [
        'service_type_id',
        'service_id',
        'debit_product_id',
        'required_amount'
    ];


    use HasFactory;


    public function service()
    {
        return $this->belongsTo(Service::class);
    }

    public function serviceType()
    {
        return $this->belongsTo(ServiceType::class);
    }

    public function product()
    {
        return $this->belongsTo(DebitProduct::class,'debit_product_id','id');
    }

}

app/Http/Controllers/ServiceProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\DebitProduct;
use App\Models\ServiceProduct;
use Illuminate\Http\Request;
use App\Models\ServiceType;



class ServiceProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = ServiceProduct::with('service','serviceType','product')->orderByDesc('created_at')->get();

        return view('service-products.index',['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $serviceTypes = ServiceType::get();
        $debitProducts = DebitProduct::get();
        
        return view('service-products.create', [
            'serviceTypes' => $serviceTypes,
            'products' => $debitProducts,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->validate([
            'service_type_id' => 'required',
            'service_id' => 'required',
            'serviceProducts.*.debit_product_id' => 'required',
            'serviceProducts.*.required_amount' => 'required',
        ]);


        if(isset($input['serviceProducts']) && count($input['serviceProducts'])){
            foreach($input['serviceProducts'] as $serviceProduct){
                
                $inputDetail = [
                    'service_type_id' => $input['service_type_id'],
                    'service_id' => $input['service_id'],
                    'debit_product_id' => $serviceProduct['debit_product_id'],
                    'required_amount' => $serviceProduct['required_amount'],
                ];

                ServiceProduct::create($inputDetail);
            }
        }
      
        return redirect()->route('service-products.index');
    

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ServiceProduct  $serviceProduct
     * @return \Illuminate\Http\Response
     */
    public function show(ServiceProduct $serviceProduct)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ServiceProduct  $serviceProduct
     * @return \Illuminate\Http\Response
     */
    public function edit(ServiceProduct $serviceProduct)
    {
        return view('service-products.edit', ['serviceProduct' => $serviceProduct]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ServiceProduct  $serviceProduct
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ServiceProduct $serviceProduct)
    {
        $input = $request->validate([
            'service_type_id' => 'nullable',
            'service_id' => 'nullable',
            'debit_product_id' => 'nullable',
            'required_amount' => 'nullable',
        ]);

        if($serviceProduct->update($input)){
            return view('service-products.index');
        }

        abort(422,'Yangilashda xatolik');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ServiceProduct  $serviceProduct
     * @return \Illuminate\Http\Response
     */
    public function destroy(ServiceProduct $serviceProduct)
    {
        //
    }
}

resources/views/service-products/create.blade.php
@extends('layouts.app')
@section('content')
	<div class="pd-20 card-box mb-30">
		<div class="clearfix mb-30">
			<div class="text-center">
				<h4 class="text-blue h4"> Xizmatga yangi mahsulot biriktirish </h4>
			</div>
		</div>
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
				@if ($errors->has('email'))
				@endif
			</div>
		@endif
		<form method="POST" action="{{ route('service-products.store') }}">
			@csrf
			<div id="discounts">
				<div class="row">
					<div class="col-md-4 col-sm-12">
						<div class="form-group">
							<select name="service_type_id" class="form-control serviceTypeSelect" id="service_type_id">
                                <option value="">Xizmat turini tanlang</option>
                                @foreach($serviceTypes as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
						</div>
					</div>
					<div class="col-md-4 col-sm-12">
						<div class="form-group">
							<select name="service_id" class="form-control serviceNameSelect" id="service_id">
                                <option value="">Xizmat nomi</option>
                            </select>
						</div>
					</div>
				</div>
				<div id="serviceProducts">	
					<div class="row">
						<div class="col-md-4 col-sm-12">
							<div class="form-group">
								<select name="serviceProducts[0][debit_product_id]" class="form-control" id="debit_product_id">
									<option value="">Mahsulotni tanlang</option>
									@foreach($products as $item)
										<option value="{{ $item->id }}">{{ $item->name }}</option>
									@endforeach	

								</select>
							</div>
						</div>
						<div class="col-md-3 col-sm-12">
							<div class="form-group">
								<input class="form-control"  type="number"  placeholder="Kerakli miqdor" name="serviceProducts[0][required_amount]">
							</div>
						</div>
						<div class="col-md-2">
							<button  type="button" class="btn btn-success" id="addServiceProduct"><i class="fa fa-plus"></i></button>
							<button  type="button" class="btn btn-danger" id="rmServiceProduct"><i class="fa fa-minus"></i></button>
						</div>
					</div>
				</div>
			</div>
			<hr>

			<br>
			<div class="row">
				<div class="form-group offset-11">
					<button type="submit" class="btn btn-primary">Saqlash</button>
				</div>
			</div>
		</form>
	</div>
@endsection

resources/views/service-products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="pd-20 card-box mb-30">
	<div class="clearfix mb-20">
		<div class="text-center">
			<h4 class="text-blue h4">Xizmatlarga ketadigan mahsulotlarni biriktirish</h4>
		</div>
		<div class="pull-right">
			<a href="{{ route('service-products.create') }}" class="btn btn-primary btn-sm scroll-click">Mahsulot biriktirish  </a>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-bordered table-striped" id="myTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Xizmat turi nomi</th>
					<th>Xizmat nomi</th>
					<th>Mahsulot nomi</th>
					<th>Kerakli soni</th>
					<th>Biriktirilgan vaqt</th>
					{{-- <th>Amallar</th> --}}
				</tr>
			</thead>
			<tbody>
				@forelse($products as $item)
					<tr>
						<td>{{ $loop->index + 1 }}</td>
                    	<td> {{ $item->serviceType->name }}</td>
                        <td> {{ $item->service->name }} </td>
						<td> {{ $item->product->name }}</td>
						<td> {{ $item->required_amount }}</td>
						<td> {{ $item->created_at }}</td>
						
                        {{-- <td class="d-flex">
                            <a href="" class="btn btn-sm btn-success mr-2">Tahrirlash</a>
                            <form action="{{ route('debits.destroy',  $item->id) }}" method="post" onsubmit="return confirm('Сиз ростдан ҳам ушбу маълумотни ўчиришни хохлайсизми ?')">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-sm btn-danger">
                                    <span class="">O'chirish</span>
                                </button>
                            </form>
                        </td> --}}
					</tr>
				@empty
					<tr>
						<td colspan="8">Ma'lumotlar topilmadi</td>
					</tr>
				@endforelse
			</tbody>

		</table>
	</div>
</div>
@endsection


	<!-- <script src="/vendor/datatables/buttons.server-side.js"></script> -->