routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PatientServiceController;
use App\Http\Controllers\PatientServiceAjaxController;
use App\Http\Controllers\ResourceController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ServiceTypesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PatientSenderController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\PatientCardController;
use App\Http\Controllers\SmsController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\DebitController;
use App\Http\Controllers\DebitProductsController;
use App\Http\Controllers\ServiceProductController;
use App\Http\Controllers\OutputController;
use App\Http\Controllers\UserController;
use App\Models\Patient;
use Carbon\Carbon;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ping', function(){

    return Carbon::now()->startOfYear()->toDateString();
});

Route::get('/prices/{service_type_id}', [PrintController::class,'generatePrices']);



Route::post('/webhook/{token}/callback', [TelegramController::class,'handle'])->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]);;


// Route::post('/patient-services/export', [PatientServiceAjaxController::class, 'index'])->name('patient-services.api.index');
Route::get('patient/profile/{code?}',[PatientController::class,'profile'])->name('patient.login');
Route::get('patient/detail',[PatientController::class,'profileDetail'])->name('patient.profile');
Route::get('patient/logout/{id}',[PatientController::class,'logout'])->name('patient.logout');


Route::middleware(['auth'])->group(function(){

    Route::get('/', [HomeController::class,'index'])->name('home');
     Route::get('/home', [HomeController::class,'index'])->name('home.welcome');
    Route::get('/dashboard/{range}', [DashboardController::class,'statistic'])->name('dashboard.statistic');

    Route::get('/sms/index', [SmsController::class, 'index'])->name('sms.index');
    Route::post('/sms/send', [SmsController::class, 'send'])->name('sms.send');
    Route::get('/seach-patients/{phone}', [SmsController::class, 'ajax']);


    Route::resource('patients',PatientController::class);


    Route::resource('service-types',ServiceTypesController::class);



    Route::get('patients', [PatientController::class,'index'])->name('patients.index');

    // Route::delete('patients-services/delete/{patient_service}', [PatientServiceController::class,'delete'])->name('patient-services.delete');

    //repetition
    Route::get('repetition/create/{patient_id?}', [PatientServiceController::class,'createRepetetion'])->name('repetition.create');
    Route::post('repetition', [PatientServiceController::class,'storeRepetetion'])->name('repetition.store');


    Route::resource('patient-services',PatientServiceController::class);
    Route::prefix('excel')->group(function () {
        Route::get('patient-services',[PatientServiceController::class,'excelExport'])->name('patient-services.excel'); 
    });
    Route::resource('doctors',DoctorController::class);
    Route::resource('services',ServiceController::class);


    Route::get('/print/{service_id}', [PrintController::class, 'printConclusion'])->name('printConclusion');
    Route::get('/print-recommendation/{service_id}', [PrintController::class, 'printRecommendation'])->name('printRecommendation');
    Route::get('/print/check/{patient_id}', [ PrintController::class,'printCheck'])->name('print.check');

    //payment
    Route::get('/patients-for-cashier', [ PatientServiceController::class,'patientsForCashier'])->name('patient-services.cashier');
    Route::get('/get-patient-services/{patient_id}', [ PatientServiceController::class,'getPatientServices'])->name('get-patient-services');

    Route::post('/confirm', [ PatientServiceController::class,'paymentConfirm'])->name('payment.confirm');
    Route::get('/patients-services/profile/{patient_service}', [ PatientServiceController::class,'profile'])->name('patient-services.profile');
    Route::get('/patients-services/for-patient/{patient_service}', [ PatientServiceController::class,'forPatient'])->name('patient.service-details');

    //conclusion

    Route::get('/payed-services', [ PatientServiceController::class,'getPayedServices'])->name('patient-services.payed');
    Route::post('/save-conlusion', [ PatientServiceController::class,'saveConclusion'])->name('patient-services.conclusion');


    Route::get('/resources/cities/{region_id}', [ResourceController::class,'getCitiesByRegion']);
    Route::get('/resources/diagnostics/{service_type_id}', [ResourceController::class,'getDiagnosticTypes']);
    Route::get('/resources/services/{service_type_id}/{diagnostic_type_id?}', [ResourceController::class,'getServices']);
    Route::get('/resources/service-types', [ResourceController::class,'getServiceTypes']);
    Route::get('/resources/debit-products', [ResourceController::class,'getDebitProducts']);



    //reports

    Route::get('/reports/all', [ReportController::class, 'all'])->name('reports.all');
    Route::get('/reports/by-patient-senders', [ReportController::class, 'bySenders'])->name('reports.bysenders');




    Route::resource('patient-senders',PatientSenderController::class);

    Route::get('/sended-patients/{patient_sender}', [PatientServiceController::class, 'getSendedPatients'])->name('patients.sended');

    Route::resource('discounts',DiscountController::class);

    Route::resource('cards',PatientCardController::class);

    // debits
    Route::resource('/debits', DebitController::class);
    // Route::get('/debits/{id}/edit', [DebitController::class,'createRepetetion'])->name('repetition.create');

    // debit_products
    Route::resource('/debit-products', DebitProductsController::class);


    Route::resource('/service-products', ServiceProductController::class);

    
    Route::get('/outputs', [OutputController::class,'index']);

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class,'index'])->name('users.index');
        Route::post('/', [UserController::class,'store'])->name('users.store');
        Route::get('/create', [UserController::class,'create'])->name('users.create');
    });
    

});



Auth::routes();

app/Http/Controllers/PatientServiceController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\PatientServicesDataTable;
use App\Models\PatientService;
use App\Models\ServiceType;
use App\Models\Patient;
use App\Models\PatientSender;
use App\Models\User;
use App\Models\PatientCard;
use App\Repositories\PatientServiceRepository;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\PatientService as ServicePatient;
use App\Events\GivedConclusion;
use App\Events\PatientServicePayed;
use App\Jobs\NewOutputRegisteredJob;
use App\Services\FileService;
use DOMDocument;
use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\PatientServiceExport;




class PatientServiceController extends Controller
{

    private $repo;
    private $model;
    private $servicePatient;

    public function __construct(PatientServiceRepository $repo, PatientService $model, ServicePatient $servicePatient)
    {
        $this->repo = $repo;
        $this->model = $model;
        $this->servicePatient = $servicePatient;
        
        ini_set('memory_limit', '-1');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function index(PatientServicesDataTable $dataTable)
    // {

    //     // $patientServices = PatientService::with('patient', 'service')->orderBy('created_at','desc')->get();
    //     // // dd($patientServices[0]->status);
    //     // return view('patients.index', [
    //     //     'patientServices' => $patientServices
    //     // ]);


    //     return $dataTable->render('patient-services.index');


    //     // return view('patients.index');
    // }

    public function index(Request $request)
    {
        $perPage = 30;

        $filters = $request->validate([
            'full_name' => 'nullable',
            'phone' => 'nullable',
            'status' => 'nullable',
            'start_date' => 'nullable',
            'end_date' => 'nullable',
            'service_type' => 'nullable',
        ]);

        // if($filters){
        //     return $filters;
        // }

       
        $query =  PatientService::with('patient', 'service','service.type','status','patientSender','patient.user');

        if(isset($filters['status'])){
            $query->where('service_status_id',$filters['status']);
        }

            
        if ($request->filled('phone')) {
         
            $query->whereHas('patient', function($q) use($request){
                $q->where('phone', 'like', '%' . $request->input('phone') . '%');
            });
        }

        if ($request->filled('full_name')) {
            $fullName = $request->input('full_name');
            $query->whereHas('patient', function($q) use($fullName){
                $q->whereRaw("CONCAT(first_name, ' ', last_name) LIKE ?", ["%$fullName%"]);
            });
            // Filter by the combined full_name (first_name + last_name)
         
        }

        if ($request->filled('date_from')) {
            $query->whereDate('created_at', '>=', Carbon::parse($request->input('date_from'))->toDateString());
        }
    
        if ($request->filled('date_to')) {
            $query->whereDate('created_at', '<=', Carbon::parse($request->input('date_to'))->toDateString());
        }
       // filters

       $patientServices = $query->orderBy('created_at','desc')->paginate($perPage);



        // $patientServices = PatientService::with('patient', 'service')->orderBy('created_at','desc')->get();
        // // dd($patientServices[0]->status);
       
        return view('patient-services.list', [
            'patientServices' => $patientServices,
            'perPage' => $perPage
        ]);


      


        // return view('patients.index');
    }

    public function patientsForCashier()
    {
        $patients =  $this->repo->patientsForCashier();

        return view('patient-services.payment.index', [
            'patients' => $patients
        ]);
    }

    public function getPatientServices($patient_id)
    {

        $patient = $this->repo->getPatientServices($patient_id);

        return view('patient-services.payment.confirm', [
            'patient' => $patient
        ]);
    }

    public function paymentConfirm(Request $request)
    {
        $patient_id = $request->input('patient_id');
        $patientServices = PatientService::where('patient_id',$patient_id)->registered();

        
        $patientServices->each(function ($item){
        
           $updateItem =  $item->update(['service_status_id'=> $this->model::STATUS_PAYED]);
            
           if($updateItem){
                event(new PatientServicePayed($item));
           }

           NewOutputRegisteredJob::dispatch($item);
        });



        if($patientServices){
            return redirect()->route('patient-services.cashier');
        }

        return 'Error occured';
    }

    public function saveConclusion(Request $request)
    {

        $inputs = $request->validate([
            'patient_service_id'=> 'required|integer',
            'conclusion'=> 'nullable',
            'conclusion_file' => 'nullable|mimes:pdf|max:4096', 
            'recommendation' => 'nullable'
        ]);

     

        $patientService = $this->model::findOrFail($inputs['patient_service_id']);

        $recommendation = (isset($inputs['recommendation']) && strlen($inputs['recommendation'])) >= 40 ?  $inputs['recommendation'] : null;
    

        $patientService->update([
            'conclusion'=>  $inputs['conclusion'],
            'service_status_id' => $this->model::STATUS_CONCLUSED,
            'recommendation' => $recommendation
        ]);

        if($patientService){

            if($request->hasFile('conclusion_file')){
                $file = $request->file('conclusion_file');

                // Generate a unique name for the file
                $fileName = '/conclusions/conclusion_file_' . time() . '.' . $file->getClientOriginalExtension();

                // Store the file in the storage/app/public directory
                if($file->storeAs('public', $fileName)){

                    $patientService->update([
                        'conclusion_file'=>  $fileName,
                    ]);

                    event(new GivedConclusion($patientService));
                }
            } else {
                $saveFile = FileService::saveConclusion($patientService);
          
                if($saveFile){
                    event(new GivedConclusion($patientService));
                }
            }
          
        
            if(auth()->user()->isReception()){
                return redirect()->route('patient-services.index');        
            }
            
            return redirect()->route('patient-services.payed');
        }

        return 'Error occured';
    }

    public function getPayedServices()
    {
        $user  = Auth::user();
        $service_type_id = $user->doctor->service_type_id;
        $patientServices = $this->repo->getPayedServices($service_type_id);

        return view('patient-services.conclusion.index', [
            'patientServices' => $patientServices
        ]);
    }

    public function forPatient($patientService)
    {
        
        $user = auth()->user();

        if($user && $user->patient){
            
            $patientIDs = Patient::where('user_id', $user->id)->pluck('id')->toArray();
            $patientService = PatientService::where('id',$patientService)->with('patient','service','status')->first();

            if(in_array($patientService->patient_id, $patientIDs)){
                 return view('patients.service',[
                    'patientService' => $patientService
                ]);
            }

        }
        
        abort(404);
      
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($patient_id = null)
    {
        $serviceTypes = ServiceType::get();
        $patientSenders = PatientSender::active()->get();
        $patientCards = PatientCard::with('patient')->get();
        $lastCard = $patientCards->sortBy('created_at')->toArray();
        $lastCardNumber = 10000;
        if(count($patientCards)){
            $lastCardNumber = end($lastCard)['number'];
        }
        if($patient_id) {
            $patient = Patient::find($patient_id);
        }
        
        return view('patient-services.create', [
            'services' => $serviceTypes,
            'patient' => ($patient_id) ? $patient : null,
            'patientSenders' => $patientSenders,
            'patientCards' => $patientCards,
            'lastCardNumber' => $lastCardNumber
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $inputs = $request->validate([
            'pass_seria'=> 'nullable',
            'pass_number'=> 'nullable',
            'first_name'=>'required',
            'last_name'=>'required',
            'patronymic'=>'nullable',
            'birth_date'=>'required',
            'gender'=>'required',
            'phone'=>'required|unique:patients',
            'services' => 'required',
            'doctor' => 'nullable',
            'patient_sender_id' => 'nullable',
            'loyality_card_number' => 'integer|nullable',
            'chain_id' => 'nullable',
            'source' => 'required',
        ]);

        // if($request->has(['pass_seria', 'pass_number'])){
        //     $inputs['passport'] = $inputs['pass_seria'].$inputs['pass_number'];
        // }

        $fields  = Arr::except($inputs,['_token', 'services', 'source','doctor', 'patient_sender_id','loyality_card_number','chain_id']);

        $patient = Patient::create($fields);
        
        if($patient){

resources/views/patient-services/conclusion/confirm.blade.php
@extends('layouts.app')

@section('content')

	<div class="pd-20 card-box mb-30">
       <div class="text-center col-lg-9 col-md-9 offset-1">
            <div class="clearfix mb-20">
                <div class="text-center">
                    <h4 class="text-blue h4">Mijoz haqida ma'lumot</h4>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Mijoz ID raqami</th>
                        <th>Mijoz familiyasi</th>
                        <th>Mijoz ismi</th>
                        <th>Mijoz tug'ilgan sanasi</th>
                        <th>Mijzo jinsi</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $patientService->patient->id }}</td>
                        <td> {{ $patientService->patient->last_name }}</td>
                        <td> {{ $patientService->patient->first_name }}</td>
                        <td> {{ $patientService->patient->birth_date }}</td>
                        <td> {{ $patientService->patient->genderLabel }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="clearfix mb-20">
                <div class="text-center">
                    <h4 class="text-blue h4">Xulosa berilishi kerak bo'lgan</h4>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Xizmat turi</th>
                        <th>Xizmat nomi</th>
                        <th>Xizmat narxi</th>
                        <th>Xizmat holati</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td> 1 </td>
                        <td> {{ $patientService->service->type->name }}</td>
                        <td> {{ $patientService->service->name }}</td>
                        <td> {{ $patientService->service->price }}</td>
                        <td> {{ $patientService->status->name }}</td>
                    </tr>
                </tbody>

            </table>
            <h4 class="text-blue h4">Tekshiruv xulosasi</h4>
            <div id="toolbar-container"></div>
            <div id="conclusion" style="border:1px solid #dee2e6;"></div>
       
            
            <form action="{{ route('patient-services.conclusion') }}" method="post" id="conclusionForm">
                @csrf
                <input type="hidden" name="patient_service_id" value="{{ $patientService->id }}">
                <textarea  name="conclusion" style="display:none" id="editorConclusion"></textarea>
                <br>
                <h4 class="text-blue h4">Shifokor tavsiyasi</h4>
                <textarea  name="recommendation" style="display:none" id="editorRecommendation"></textarea>
                <div id="toolbar-container-recommendation"></div>
                <div id="recommendation" style="border:1px solid #dee2e6;"></div>
                <br><br>
                <div class="form-group offset-10 align-right mt-20">
                    <button type="button"  onclick="submitForm()" class="btn btn-primary">Tasdiqlash</button>
                </div>
            </form>
       </div>
    </div>

    <script>
        DecoupledEditor
            .create( document.querySelector( '#conclusion' ) )
            .then( editor => {
                const toolbarContainer = document.querySelector( '#toolbar-container' );

                toolbarContainer.appendChild( editor.ui.view.toolbar.element );
            } )
            .catch( error => {
                console.error( error );
            } );

            DecoupledEditor
            .create( document.querySelector( '#recommendation' ) )
            .then( editor => {
                const toolbarContainer = document.querySelector( '#toolbar-container-recommendation' );

                toolbarContainer.appendChild( editor.ui.view.toolbar.element );
            } )
            .catch( error => {
                console.error( error );
            } );


            function submitForm(){
                var textConclusion =  document.getElementById('conclusion').innerHTML;
                var textRecommendation =  document.getElementById('recommendation').innerHTML;
 
                var modifiedConclusion = removeSvgElements(textConclusion);
                var modifiedRecommendation = removeSvgElements(textRecommendation);

                document.getElementById('editorConclusion').value = modifiedConclusion;
                document.getElementById('editorRecommendation').value = modifiedRecommendation;
                document.getElementById("conclusionForm").submit();

            }

            function removeSvgElements(htmlString) {
                // create a temporary div element to hold the HTML content
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = htmlString;

                // get all SVG elements
                const svgElements = tempDiv.querySelectorAll('svg');

                // remove each SVG element
                svgElements.forEach((svgElement) => {
                    svgElement.remove();
                });

                // return the modified HTML string
                return tempDiv.innerHTML;
            }
    </script>
@endsection

resources/views/patient-services/conclusion/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="pd-20 card-box mb-30">
		<div class="clearfix mb-20">
			<div class="text-center">
				<h4 class="text-blue h4">Shifokor xulosasi uchun xizmatlar</h4>
			</div>
		</div>
		<table class="table table-bordered" id="myTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Mijoz ismi</th>
					<th>Xizmat turi</th>
					<th>Xizmat nomi</th>
					<th>Xizmat narxi</th>
					<th>Xizmat holati</th>
				</tr>
			</thead>
			<tbody>
				@forelse($patientServices as $patientService)
					<tr>
						<td>{{ $loop->index+1 }}</td>
						<td>
							<a href="{{ route('patient-services.show',['patient_service'=> $patientService->id]) }}">
								{{ $patientService->patient->last_name.' '.$patientService->patient->first_name }}
							</a>
						</td>
						<td> {{ $patientService->service->type->name }}</td>
						<td> {{ $patientService->service->name }}</td>
						<td> {{ $patientService->service->price }}</td>
						<td> {{ $patientService->status->name }}</td>
					</tr>
				@empty
					<tr>
						<td colspan="6">Ma'lumotlar topilmadi</td>
					</tr>
				@endforelse	
			</tbody>
			
		</table>
	</div>	
@endsection